In [1]:
import h5py
import yt
import numpy as np

In [2]:
ds=yt.load("Cholla/30.h5")

YTUnidentifiedDataType: Could not determine input format from 'Cholla/30.h5'

In [3]:
f1 = h5py.File("Cholla/30.h5",'r') 

# Exploration
### Keys Explorations

In [4]:
f1.keys()

<KeysViewHDF5 ['Energy', 'GasEnergy', 'density', 'momentum_x', 'momentum_y', 'momentum_z']>

In [10]:
f1["density"]

<HDF5 dataset "density": shape (128, 128, 128), type ">f8">

In [8]:
f1['Energy']

<HDF5 dataset "Energy": shape (128, 128, 128), type ">f8">

In [13]:
f1['GasEnergy']

<HDF5 dataset "GasEnergy": shape (128, 128, 128), type ">f8">

In [18]:
f1['momentum_x']

<HDF5 dataset "momentum_x": shape (128, 128, 128), type ">f8">

In [15]:
f1['momentum_y']

<HDF5 dataset "momentum_y": shape (128, 128, 128), type ">f8">

In [16]:
f1['momentum_z']

<HDF5 dataset "momentum_z": shape (128, 128, 128), type ">f8">

In [35]:
np.array(f1['momentum_z'])

array([[[-2.47833179, -2.48605826, -2.47835298, ...,  0.75467063,
          0.76908826,  0.7941337 ],
        [-2.53182009, -2.50891021, -2.47472496, ...,  0.76330101,
          0.77901473,  0.80526378],
        [-2.52516998, -2.46789848, -2.41604529, ...,  0.76739041,
          0.7855327 ,  0.81165471],
        ...,
        [-0.49569081, -0.48839966, -0.48619897, ...,  1.20644842,
          1.19533   ,  1.19086458],
        [-0.48879041, -0.4790502 , -0.47384578, ...,  1.28491827,
          1.27058405,  1.25350641],
        [-0.48240852, -0.47112043, -0.46505248, ...,  1.44722382,
          1.42373705,  1.37959027]],

       [[-2.65102882, -2.63657818, -2.61003214, ...,  0.75917843,
          0.7729766 ,  0.79733532],
        [-2.66549434, -2.60576047, -2.5441322 , ...,  0.76794484,
          0.78282734,  0.80835636],
        [-2.6144742 , -2.52320383, -2.45441249, ...,  0.77220731,
          0.78922941,  0.8149133 ],
        ...,
        [-0.51553461, -0.51021211, -0.51416976, ...,  

### Attributes Exploration

In [5]:
f1.attrs.keys()

<KeysViewHDF5 ['bounds', 'dims', 'dims_local', 'domain', 'dt', 'dx', 'gamma', 'n_step', 'offset', 't']>

In [22]:
dims=f1.attrs["dims"]

In [26]:
f1.attrs["bounds"]

array([-5., -5., -5.])

In [27]:
f1.attrs["dims_local"]

array([128, 128, 128], dtype=int32)

In [28]:
f1.attrs["domain"]

array([10., 10., 10.])

In [29]:
f1.attrs["dt"]

array([1.])

In [30]:
f1.attrs["dx"]

array([0.078125, 0.078125, 0.078125])

In [31]:
f1.attrs["gamma"]

array([1.6666667])

In [32]:
f1.attrs["n_step"]

array([25379], dtype=int32)

In [33]:
f1.attrs["offset"]

array([0, 0, 0], dtype=int32)

In [34]:
f1.attrs["t"]

array([30000.])

# Construction
### Mesh Structure Construction

### Field Match

In [23]:
data = {n: v[()].T for n, v in f1.items() if v.shape == tuple(dims)}

In [25]:
data.keys()

dict_keys(['Energy', 'GasEnergy', 'density', 'momentum_x', 'momentum_y', 'momentum_z'])

### Geometry Specification

### Data Export

# Visualization